version: '3.7'
services:
    app:
        container_name: challenge-dashboard
        build:
          context: .
        restart: always
        volumes:
            - '.:/app'
        ports:
            - '3000:3000'

